language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update --cache-version=2.37
gemfile:
  - Gemfile
script:
    - bundle exec rake clean:all
    - bundle install
    - bundle exec rake pod:install
    - bundle exec rake spec
